### ISSUE TITLE
Trouble building glew.c

### ISSUE THREAD

**Issue by JeffBail** [nvpro-samples/gl_multicast#1]
I'm having some troubling building glew.c with Studio 2015:
1>C:\GameworksVR-1.1\vr_sli_ogl\shared_sources\glew\src\glew.c(14565): error C2373: 'glewGetErrorString': redefinition; different type modifiers
1>  C:\GameworksVR-1.1\vr_sli_ogl\shared_sources\glew\include\GL/glew.h(26314): note: see declaration of 'glewGetErrorString'
1>C:\GameworksVR-1.1\vr_sli_ogl\shared_sources\glew\src\glew.c(14579): error C2373: 'glewGetString': redefinition; different type modifiers
1>  C:\GameworksVR-1.1\vr_sli_ogl\shared_sources\glew\include\GL/glew.h(26315): note: see declaration of 'glewGetString'
1>C:\GameworksVR-1.1\vr_sli_ogl\shared_sources\glew\src\glew.c(14605): error C2373: 'glewInit': redefinition; different type modifiers
1>  C:\GameworksVR-1.1\vr_sli_ogl\shared_sources\glew\include\GL/glew.h(26303): note: see declaration of 'glewInit'
1>C:\GameworksVR-1.1\vr_sli_ogl\shared_sources\glew\src\glew.c(14624): error C2373: 'glewIsSupported': redefinition; different type modifiers
1>  C:\GameworksVR-1.1\vr_sli_ogl\shared_sources\glew\include\GL/glew.h(26304): note: see declaration of 'glewIsSupported'

It looks like in the .c GLEWAPIENTRY adds __stdCall but this isn't set in the .h which is what I think is leading to the error. I did my cmake from the build_all directory of the GameworksVR-1.1 install. Is there any configuration I might have missed?

**Comment by pixeljetstream** [comment]
closing, no longer using glew
