### ISSUE TITLE
build time failure CMakeLists_include.txt file missing

### ISSUE THREAD

**Issue by drjoms** [nvpro-samples/gl_multicast#2]
Hello.

I am just a user, I am not a programmer.
I git cloned the project(tried other programs from nvpro-samples)

cmake .

I get this:

---

-- Processing Project gl_multicast:
CMake Error at CMakeLists.txt:21 (INCLUDE):
  include could not find load file:

```
/home/dimko/games/benchmarks/vulkan/gl_multicast/../
```

shared_sources/CMakeLists_include.txt

CMake Error at CMakeLists.txt:22 (add_subdirectory):
  add_subdirectory given source
  "/home/dimko/games/benchmarks/vulkan/gl_multicast/../shared_sources" which
  is not an existing directory.

CMake Error at CMakeLists.txt:25 (_add_project_definitions):
  Unknown CMake command "_add_project_definitions".

-- Configuring incomplete, errors occurred!
See also "/home/dimko/games/benchmarks/vulkan/gl_multicast/CMakeFiles/CMakeOutput.log".

log file:
[Uploading CMakeOutput.txt…]()

Thanks!
Dmitri

**Comment by drjoms** [comment]
github page is trying to parse output and fails to  do it.
please read my message with no formatting.
Log file included.

**Comment by iesser** [comment]
Hi Dmitri,

for this project to work, you need the shared_sources and shared_external directories available under nvpro_samples. These directories need to be placed next to the gl_multicast folder.

Kind Regards,
  Ingo Esser

**Comment by drjoms** [comment]
Hello Ingo,

I think previous problem was solved.  I did not realise folder at top was a 'requirement' pretty much, sorry.
I shall report another problem in a new post. Just reporting back solution:

dimko@myPC ~/games/benchmarks/vulkan/gl_multicast $ ls
CMakeCache.txt  CMakeFiles  CMakeLists.txt  common.h  compose.frag.glsl  compose.vert.glsl  doc  main.cpp  README.md  scene.frag.glsl  scene.vert.glsl  shared_sources
dimko@myPC ~/games/benchmarks/vulkan/gl_multicast $ git clone https://github.com/nvpro-samples/shared_sources
Cloning into 'shared_sources'...
remote: Counting objects: 722, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 722 (delta 3), reused 0 (delta 0), pack-reused 700
Receiving objects: 100% (722/722), 2.93 MiB | 1.45 MiB/s, done.
Resolving deltas: 100% (438/438), done.
Checking connectivity... done.

cmake ./

---

-- Processing Project gl_multicast:
-- found sub-folder shared_sources
-- BASE_DIRECTORY = /home/dimko/games/benchmarks/vulkan/gl_multicast
-- CMAKE_CURRENT_SOURCE_DIR = /home/dimko/games/benchmarks/vulkan/gl_multicast
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so
-- Looking for XOpenDisplay in /usr/lib64/libX11.so;/usr/lib64/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib64/libX11.so
-- Found OpenGL: /usr/lib64/libGL.so  
-- Found GLEW: /home/dimko/games/benchmarks/vulkan/gl_multicast/shared_sources/glew/include  
-- Could NOT find GLFW (missing:  GLFW_INCLUDE_DIR GLFW_LIBRARY) 
-- found Glew source code. Using it instead of library
-- --> using package AntTweakBar
CMake Warning at shared_sources/cmake/FindAntTweakBar.cmake:72 (message):

```
    AntTweakBar not found. 
    The ANTTWEAKBAR folder you would specify with ANTTWEAKBAR_LOCATION should contain:
    - lib folder: containing the ANTTWEAKBAR[64_]*.dll
    - include folder: containing the include files
    OR this folder could directly contain the dll and headers, put together
    For now, samples will run without additional UI. But that's okay ;-)
```

Call Stack (most recent call first):
  shared_sources/CMakeLists_include.txt:227 (find_package)
  CMakeLists.txt:38 (_add_package_AntTweakBar)

-- Could NOT find ANTTWEAKBAR (missing:  ANTTWEAKBAR_INCLUDE_DIR ANTTWEAKBAR_DLL) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dimko/games/benchmarks/vulkan/gl_multicast

**Comment by iesser** [comment]
Hi Dmitri,

If you also want AntTweakBar to work, please also put the shared_external folder next to the shared_sources folder.

Kind Regards,
  Ingo

**Comment by drjoms** [comment]
I want it to work. I'd assume once cmake is done, program is ready for a
build. Yet compilation fails.

That is my problem at the moment, that I can't compile even minimum at this time.

Dmitri

**Comment by pixeljetstream** [comment]
closing, framework (shared_sources) currently has no linux support
